---
info:
  component: Default Single Swagger Document Server for MicroService

spring:
  profiles: default

server:
  port: 8014

documentation: 
  swagger: 
    services:   
      - 
        name: PetService
        url: http://petstore.swagger.io/v2/swagger.json
        version: 2.0
      - 
        name: FoodService
        url: http://petstore.swagger.io/v2/swagger.json
        version: 2.0
      - 
        name: HumanService
        url: http://petstore.swagger.io/v2/swagger.json
        version: 2.0
      - 
        name: crudapplication
        url: http://localhost:8085/v2/api-docs
        version: 2.0